# Generated by Django 4.2.21 on 2025-05-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopt", "0003_generaldonation_medicalsponsorship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipdonation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="animal_images/"),
        ),
    ]
