# Generated by Django 4.2.21 on 2025-05-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adopt", "0004_sponsorshipdonation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaldonation",
            name="slip_image",
            field=models.ImageField(blank=True, null=True, upload_to="slips/"),
        ),
        migrations.CreateModel(
            name="AdoptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("subdistrict", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("household_info", models.TextField()),
                ("other_pets", models.TextField()),
                ("property_description", models.TextField()),
                ("job_and_hours", models.TextField()),
                ("motivation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_requests",
                        to="adopt.strayanimal",
                    ),
                ),
            ],
        ),
    ]
