# Generated by Django 4.2.21 on 2025-05-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopt", "0006_rename_created_at_adoptionrequest_submitted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="blog/")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="adoptionrequest",
            old_name="submitted_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="adoptionrequest",
            name="job_and_hours",
        ),
        migrations.RemoveField(
            model_name="adoptionrequest",
            name="pet",
        ),
        migrations.AddField(
            model_name="adoptionrequest",
            name="jobs",
            field=models.CharField(default="Not specified", max_length=200),
        ),
        migrations.AddField(
            model_name="adoptionrequest",
            name="pets",
            field=models.ManyToManyField(
                related_name="adoption_requests", to="adopt.strayanimal"
            ),
        ),
        migrations.AlterField(
            model_name="adoptionrequest",
            name="other_pets",
            field=models.TextField(blank=True),
        ),
    ]
